models/area.py
from config.db import db
from models.foto import Foto
from models.video import Video
from models.juego import Juego

class Area(db.Model):
    idarea = db.Column(db.Integer, primary_key=True)
    nomarea = db.Column(db.String(45),nullable=False,unique=True)
    descarea = db.Column(db.String(250),nullable=False)

    # RELACION ONETOMANY CHILD (con evento)
    evento = db.relationship( "Evento", back_populates="areas")
    evento_id = db.Column(db.Integer, db.ForeignKey('evento.idevento'), comment="evento del area i", nullable=True)
    
    # ONETOMANY PARENT (con foto)
    fotos = db.relationship("Foto", back_populates="area", cascade="all, delete")
    # ONETOMANY PARENT (con video)
    videos = db.relationship("Video", back_populates="area", cascade="all, delete")

    # ONETOMANY PARENT (con juego)
    juegos = db.relationship("Juego", back_populates="area", cascade="all, delete")

    def save(self):
        """ se agrega a la base de datos"""
        if not self.idarea:
            db.session.add(self)
        db.session.commit()

    def remove(self):
        """ se elimina de la base de datos"""
        if self.idarea:
            db.session.delete(self)
            db.session.commit()

    def agregar_foto(self,titulo,url,descripcion):
        """ agrega un area al evento"""
        Foto(  
                titulof= titulo,
                urlf= url,
                descf= descripcion,
                area = self ).save()

    def agregar_video(self,titulo,url,descripcion):
        """ agrega un area al evento"""
        Video(  
                titulov= titulo,
                urlv= url,
                descv= descripcion,
                area = self ).save()

    def agregar_juego(self,nombre,urlj,urlf,desc):
        """ agrega un area al evento"""
        Juego(  
                nomjuego=nombre,
                urljuego=urlj,
                urlimgjuego=urlf,
                descjuego=desc,
                area = self ).save()


    #  METODOS STATICOS NO REQUIEREN INSTANCIA PARA USARLOS

    @staticmethod
    def update(id, nombre, descripcion ):
        """ permite actualizar este objeto en la bd , retorna el usuario que actualizó sino retorna None"""
        area = Area.query.get(id) #buscar en la bd
        if area:
            area.nomarea = nombre
            area.descarea = descripcion
            area.save()
            return area
        return None

    @staticmethod
    def delete(id):
        """ dado un id los busca y si existe lo eliminar, retorna el usuario que eliminó sino retorna None"""
        area = Area.query.get(id)
        if area:
            area.remove()
            return area
        return None

    @staticmethod
    def search(search_query, page, per_page):
        """ busca un usuario por name"""
        query = Area.query
        if (search_query):
            query = query.filter(Area.name.like(f"%{search_query}%"))
        return query.paginate(page=page, per_page=per_page, error_out=False)

    @staticmethod
    def all():
        """trae a todos los usuarios"""
        return Area.query.all()

    @staticmethod
    def get_by_id(id):
        """ busca usuario por id"""
        return Area.query.get(id)

    @staticmethod
    def find_by_name(nombre):
        """ busca un usuario por email """
        return Area.query.filter_by(nomarea = nombre).first()

    @staticmethod
    def all_areas(evento_id):
        """ devuelve todas las areas relacionadas a un evento """
        return Area.query.filter(Area.evento_id == evento_id).all()

    @property
    def serialize(self):
       """Return object data in easily serializable format"""
       return {
           "id":self.idarea,
           "nombre": self.nomarea,
           "descripcion": self.descarea
       }

models/juego.py
from config.db import db
from models.foto import Foto
from models.video import Video

class Juego(db.Model):

    idjuego = db.Column(db.Integer, primary_key=True)
    nomjuego = db.Column(db.String(45),nullable=False,unique=True)
    urljuego = db.Column(db.String(150),nullable=False,unique=True)
    urlimgjuego = db.Column(db.String(150),nullable=False,unique=True)
    descjuego = db.Column(db.String(250),nullable=False)

    # ONETOMANY PARENT (con foto)
    fotos = db.relationship("Foto", back_populates="juego", cascade="all, delete")

    # RELACION ONETOMANY CHILD (con area)
    area = db.relationship( "Area", back_populates="juegos")
    area_id = db.Column(db.Integer, db.ForeignKey('area.idarea'), comment="foto del area i", nullable=True)

    def save(self):
        """ se agrega a la base de datos"""
        if not self.idjuego:
            db.session.add(self)
        db.session.commit()

    def remove(self):
        """ se elimina de la base de datos"""
        if self.idjuego:
            db.session.delete(self)
            db.session.commit()

    def agregar_foto(self,titulo,url,descripcion):
        """ agrega un area al evento"""
        Foto(  
                titulof= titulo,
                urlf= url,
                descf= descripcion,
                juego = self ).save()


    def __repr__(self):
        """ retorna un string que describe el objeto """
        return f'<redSocial {self.nomjuego}>'

    #  METODOS STATICOS NO REQUIEREN INSTANCIA PARA USARLOS

    @staticmethod
    def update(id, nombre,urljuego,urlimagen,descripcion):
        """ permite actualizar este objeto en la bd , retorna el usuario que actualizó sino retorna None"""
        juego = Juego.query.get(id) #buscar en la bd
        if juego:
            juego.nomjuego = nombre
            juego.urljuego = urljuego
            juego.urlimgjuego = urlimagen
            juego.descjuego = descripcion
            juego.save()
            return juego
        return None

    @staticmethod
    def delete(id):
        """ dado un id los busca y si existe lo eliminar, retorna el usuario que eliminó sino retorna None"""
        juego = Juego.query.get(id)
        if juego:
            juego.remove()
            return juego
        return None

    @staticmethod
    def search(search_query, page, per_page):
        """ busca un usuario por name"""
        query = Juego.query
        if (search_query):
            query = query.filter(Juego.name.like(f"%{search_query}%"))
        return query.paginate(page=page, per_page=per_page, error_out=False)

    @staticmethod
    def all():
        """trae a todos los usuarios"""
        return Juego.query.all()

    @staticmethod
    def get_by_id(id):
        """ busca usuario por id"""
        return Juego.query.get(id)

    @staticmethod
    def find_by_name(nombre):
        """ busca un usuario por email """
        return Juego.query.filter_by(nomjuego = nombre).first()

    @property
    def serialize(self):
       """Return object data in easily serializable format"""
       return {
           "id":self.idjuego,
           "nombre": self.nomjuego,
           "url_juego": self.urljuego,
           "url_img_juego": self.urlimgjuego,
           "descripcion": self.descjuego
       }

routes/area.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask.helpers import flash
from models.area import Area #para añadir los datos a la tabla
from utils.db import db #para guardarme la tabla en la base de datos


area= Blueprint('area',__name__)

#Defino la ruta para mostrar la impresion
@area.route('/crearArea')
def index_area():
    aux_areas=Area.query.all()
    return render_template('area.html',areas=aux_areas)

#Defino la ruta para crear un contacto
@area.route('/area', methods=['POST'])
def add_area():
    nom=request.form['name']
    # password=request.form['pasword']
    # email=request.form['email']
    new_area=Area(nom) #agrego datos a la tabla area
    db.session.add(new_area) #agrego la tabla en la base de datos
    db.session.commit() # cierro la conexion con la base de datos
    flash("se añadio un area correctamente")
    return redirect('/crearArea')

#Defino la ruta para actualizar un contacto
@area.route('/update_area/<id>',methods=['POST','GET'])
def update(id):

    aux_area=Area.query.get(id) #Busco al area en la tabla

    if(request.method=='POST'):
        aux_area.name=request.form['name']
        # aux_area.password=request.form['pasword']
        # aux_area.email=request.form['email']
        db.session.commit() # cierro la conexion con la base de datos
        flash("se actualizo un area correctamente")
        return redirect(url_for('area.index_area'))
    
    # flash("se añadio un area correctamente")
    return render_template('area_update.html',areas=aux_area)

#Defino la ruta para eliminar un contacto
@area.route('/delete_area/<id>')
def delete(id):
    aux_area=Area.query.get(id) #Busco al area en la tabla
    db.session.delete(aux_area) # eliminno desde la BD
    db.session.commit()
    flash("se elimino un area correctamente")
    return redirect(url_for('area.index_area')) #redirecciono a una funcion

templates/Conclusiones-del-evento.html
  <!-- Contenedor del testimonio -->
  {% extends 'partials/_layout.html' %}
  {% block body %}
  <!-- Info de conclusiones del evento-->
  <main>
        <div class="main-card">
            <div class="main-card-body">               
                <div id="afiche-header" class="afiche__head">
                    <h1 id="contenido" class="centrar-texto" tabindex="0">Conclusiones del evento</h1>
                </div>
                <div class="video__descripcion" tabindex="0">
                    <p>
                        El evento Generar CONciencia: conocimientos y experiencias sobre las inundaciones de La Plata trata de abordar el tema de la inundación de La Plata desde la perspectiva de los testigos y sobrevivientes.
                    </p>    
                    <p>
                        A pesar de las dificultades de los momentos vividos, del dolor y desesperación,en casi todos los relatos coinciden en rescatar la solidaridad y la fuerza para sobrellevar tal momento.
                    </p>
                    <p>
                        Seleccione alguno de las tapas de las conclusiones para acceder a dicha información.
                    </p>
                </div>
                <div class="main-card-info">
                    <div class="card-container">
                        <div role="img" class="card__diario back-conclusiones-1" tabindex="1" aria-labelledby="diario-1">
                            <!-- <img src="./img/diarios/eldia_logo.png" alt=""> -->

                            <div class="button__container button_position hide__only720">
                                <a href="/la-importancia-de-la-solidaridad" class="button__custom--fit verde-1"> La importancia de la solidaridad.</a>
                            </div>
                        </div>
                        <div role="img" class="card__diario back-conclusiones-2" tabindex="3" aria-labelledby="diario-2">
                            <!-- <img src="./img/diarios/Hoy_logo.png" alt=""> -->
                            
                            <div class="button__container button_position hide__only720">
                                <a href="/reflexiones-de-los-entrevistados" class="button__custom--fit verde-1"> Reflexiones de los entrevistados.</a>
                            </div>
                        </div>
                        <div role="img" class="card__diario back-conclusiones-3" tabindex="5" aria-labelledby="diario-3">
                            <!-- <img src="./img/diarios/Diagoanles_logo.png" alt=""> -->
                            
                            <div class="button__container button_position hide__only720">
                                <a href="/legado-memoria" class="button__custom--fit verde-1"> El legado de la memoria.</a>
                            </div>
                        </div>
                        <!-- <div class="card" tabindex="5" aria-labelledby="diario-3">
                          <div class="card__info">
                              <h3>La ayuda de la radio</h3>
                              <p>Hecho por </div>
                          <div class="button__container hide__only720">
                              <a href="/la-ayuda-de-la-radio" class="button__custom--fit verde-1">La ayuda de la radio.</a>
                          </div>
                        </div> -->
                        

                    </div>
                    <div class="card-container hide_btn">
                        <div class="button__container">
                            <a role="button" href="/la-importancia-de-la-solidaridad" tabindex="2" class="button__custom--fit verde-1" id="diario-1"> La solidaridad. </a>
                        </div>
                        <div class="button__container">
                            <a role="button" href="/reflexiones-de-los-entrevistados" tabindex="4" class="button__custom--fit verde-1" id="diario-2"> Las reflexiones. </a>
                        </div>
                        <div class="button__container">
                            <a role="button" href="/legado-memoria" tabindex="6" class="button__custom--fit verde-1" id="diario-3"> El legado de la memoria. </a>
                        </div>
                        <!-- <div class="button__container">
                          <a role="button" href="/la-ayuda-de-la-radio" tabindex="6" class="button__custom--fit verde-1" id="diario-3"> La ayuda de la radio. </a>
                        </div> -->
                        
                    </div>
                </div>

      </div>

        </div>
    <!-- boton para ir arriba -->
    {% include ('partials/_button.html') %}  
  
  </main>

  <!-- FIN Info de conclusiones del evento-->
  {% endblock %}

templates/area.html
{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for lol in messages %}
            {{lol}}
        {% endfor %}
    {% endif %}
{% endwith %}

<h1>Crear area</h1>
<form action="/area" method="POST">

    <input type="text" name="name" placeholder="WACRIBE TU NOMBRE" />
    <!-- <input type="text" name="pasword" placeholder="WACRIBE TU pasword" />
    <input type="email" name="email" placeholder="WACRIBE TU email" /> -->
    <button>save</button>
</form>
<!-- listar usuarios: los atributos son los de la BD -->
<div>
    {% for area in areas%}
    <div>
        <h5>{{area.name}}</h5>
        <div>
            <a href="{{url_for('area.update',id=area.id)}}">Update</a>
            <a href="{{url_for('area.delete',id=area.id)}}">Delete</a>
        </div>

    </div>
    {%endfor%}

</div>

templates/desastres_naturales.html
  <!-- Contenedor del testimonio -->
  {% extends 'partials/_layout.html' %}
  {% block body %}
  <!-- Info del Contenedor del video-->
  <main>
   
        <div class="main-card">
          <div class="main-card-body">
            <div id="afiche-header" class="afiche__head">
              <h1 id="contenido" tabindex="0" class="centrar-texto">Catástrofes naturales</h1>
            </div>
            
                
                <!-- detalles del video -->
                <div tabindex="0" class="grid__texto flex__container_dondeir">
                    
                    <div class="video__descripcion">
                      <p >
                        El proyecto Citadine – Ciencia ciudadana para la gestión de catástrofes y soluciones basadas en la naturaleza- desarrolló el sitio sobre catástrofes naturales. El mismo incluye  las entrevistas realizadas a testigos y sobrevivientes de la inundación de la ciudad de La Plata como de otras catástrofes del exterior. Se encuentran entrevistas de Alemania, Polonia, República Dominicana y Chile. 
                        Cliquee en el botón para acceder al sitio de Catástrofes naturales del proyecto Citadine. Se abrirá una pestaña del navegador para el acceso al mismo.
                        
                      </p>
                    </div>
                    
                   
                    <!-- 1 imagen -->
                    <div  class="grid__container__2">
                      <div class="grid__image">
                              <img tabindex="0" role="img" width="70%" height="70%" src="{{url_for('static', filename = 'img/section6/desastre.webp')}}" aria-label="Imagen del Sitio web de desastres naturales." alt="Imagen del Sitio web de desastres naturales.">
                              
                                <small class="contenedor__text" style="width: 50%; margin: 0 auto;">
                                    Foto: Sitio web de desastres naturales."
                                </small>
                        </div>
                    </div>
                    
                    <!-- boton jugar-->
                    <div tabindex="0" class="verde-4 boton" style="width: 50%;">
                      <a aria-label="Ir al sitio de Citadine -catástrofes." class="citadineAzul" style="color: rgb(255, 255, 255);" > Ir al sitio de Citadine -catástrofes </a>
                    </div>
                  
                </div>
                <!-- fin del contenedor   -->
            
          </div>
        </div>
        <!-- boton para ir arriba -->
        {% include ('partials/_button.html') %}  
  </main>
  
 <!-- FIN Info del contenedor de video -->
 {% endblock %}

templates/dondeirjuegos.html
<!-- Contenedor de juegos -->
{% extends 'partials/_layout_pc.html' %}
{% block body %}
<!-- Info de los juegos-->
<main>
  <div class="container">
    <div class="main-card" style="margin: 10rem 0; background-color: #004d40; border-radius: 2.8rem;">
      <div class="main-card-header">
        <!-- titulo de la pagina -->
        <div id="afiche-header" class="afiche__head">
          <h1 id="contenido" tabindex="0" class="centrar-texto">¿A dónde ir?</h1>
        </div>
        <!-- descripcion antes de interactuar con los juegos -->
        <div tabindex="0" class="centrar-texto">
          <p>
            Veni a descubrir los centros de encuentro más cercanos al lugar que indiques. Accedé a esta aplicación (mediante el botón ir al sitio web) que genera caminos a dichos puntos de evacuación, evitando las zonas inundables.
            Considera mapas publicados por la <abbr title="Universidad Nacional de La Plata.">UNLP</abbr> y los centros de evacuación publicados por la Municipalidad de La Plata. 
          </p>
         
        </div>
      </div>
      <!-- presentacion de los 6 juegos -->
      <div class="main-card-body">
        <div class="container-juego">
          <!-- juego 1 -->
          <div class="card">
            <img tabindex="0" role="img" class="img-juego img1"
              src="{{url_for('static', filename = 'img/section5/dondeir-tapa/dondeir.webp')}}" alt="¿Dónde ir?"
              aria-label="Tapa del sitio web caminos a refugios.">
            <div class="intro">
              <h2 tabindex="0">
                Caminos a refugios.
              </h2>
              <p tabindex="0" class="esconder-detail" style="margin-bottom:1rem">
                Esta aplicación sirve para trazar caminos de una ubicaicón a centros evacuación, evitando zonas con probabilidad de inundarse.
              </p>
              <div aria-labelledby="diario-2">
                <div class=" verde-4 esconder-detail boton">
                  <a role="button" tabindex="0" aria-label="Ir al sitio web caminos a refugios."
                    id="dondeircamino" style="color: rgb(255, 255, 255);"> Ir al sitio web</a>
                </div>
              </div>
            </div>
          </div>
          <!-- juego 2 -->
          <div class="card" tabindex="0">
            <img role="img" class="img-juego img1"
              src="{{url_for('static', filename = 'img/section5/dondeir-tapa/evacuAr.webp')}}" alt="EvacuAR."
              aria-label="Tapa del sitio web EvacuAR.">
            <div class="intro">
              <h2>
                EvacuAR
              </h2>
              <p class="esconder-detail">
                
                Aplicacion de servicios mediante el cual usted puede ver puntos de encuentro, recorridos de evacuación, zonas inundables, realizar denuncias ambientales ademas puede ver estadisticas de la pagina para informase acerca de muchas cosas.

              </p>
              <div aria-labelledby="diario-2">
                <div class="verde-4 esconder-detail boton">
                  <a role="button" tabindex="0" aria-label="Ir al sitio web EvacuAR."
                    id="dondeir2" style="color: rgb(255, 255, 255);"> Ir al sitio web</a>
                </div>
              </div>
            </div>
          </div>
          <!-- juego 3 -->
          <div class="card" tabindex="0">
            <img role="img" class="img-juego img1"
              src="{{url_for('static', filename = 'img/section5/dondeir-tapa/servicios.webp')}}" alt="Servicios."
              aria-label="Tapa del sitio web Servicios.">
            <div class="intro">
              <h2>
                Servicios
              </h2>
 
              <p class="esconder-detail">
                Aplicacion de servicios mediante el cual usted puede ver puntos de encuentro, recorridos de evacuación, zonas inundables, ademas puede realizar denuncias sobre problemas ambientales indicando la zona en la que se encuentra.
              </p>
              <div aria-labelledby="diario-2">
                <div class="verde-4 esconder-detail boton">
                  <a role="button" tabindex="0" aria-label="Ir al sitio web Servicios." 
                  id="dondeir3"
                    style="color: rgb(255, 255, 255);"> Ir al sitio web</a>
                </div>
              </div>
            </div>
          </div>
          <!-- juego 4 -->
          <div class="card" tabindex="0">
            <img role="img" class="img-juego img1"
              src="{{url_for('static', filename = 'img/section5/dondeir-tapa/zonasinundadas.webp')}}" alt="Zonas inundadas."
              aria-label="Tapa del sitio Zonas inundadas.">
            <div class="intro">
              <h2>
                Zonas inundadas
              </h2>
              <p class="esconder-detail">
                Este portal te permitirá conocer las zonas de inundación de la ciudad, puntos de evacuacion, realizar denuncias, y ver el mapa de denuncias.
              </p>
              <div aria-labelledby="diario-2">
                <div class="verde-4 esconder-detail boton">
                  <a role="button" tabindex="0" aria-label="Ir al sitio web Zonas inundadas."
                    id="dondeir4"
                    style="color: rgb(255, 255, 255);"> Ir al sitio web</a>
                </div>
              </div>
            </div>
          </div>
          <!-- juego 5 -->
          <div class="card" tabindex="0">
            <img role="img" class="img-juego img1"
              src="{{url_for('static', filename = 'img/section5/dondeir-tapa/municipalidadlaplata.webp')}}" alt=" Sitio de Municipalidad de La Plata."
              aria-label="Tapa del juego Municipalidad de La Plata.">
            <div class="intro">
              <h2>
                Municipalidad de La Plata
              </h2>
              <p class="esconder-detail">
                ofrece los mismos servicios que los otros websites pero en el citio de la municipalidad de la plata.
              </p>
              <div aria-labelledby="diario-2">
                <div class="verde-4 esconder-detail boton">
                  <a role="button" tabindex="0" aria-label="Ir al sitio web Municipalidad de La Plata."
                    id="dondeir5" style="color: rgb(255, 255, 255);">
                    Ir al sitio web</a>
                </div>
              </div>
            </div>
          </div>
          <!-- juego 7 -->
          <div class="card" tabindex="0">
            <img role="img" class="img-juego img1"
              src="{{url_for('static', filename = 'img/section5/dondeir-tapa/inundacioneslaplata.webp')}}"
              alt="Inundaciones La Plata." aria-label="Tapa del sitio web Inundaciones La Plata.">
            <div class="intro">
              <h2>
                Inundaciones La Plata
              </h2>
              <p class="esconder-detail">
                Aquí podrás observar los posibles puntos de encuentro frente a una inundación.
              </p>
              <div aria-labelledby="diario-2">
                <div class="verde-4 esconder-detail boton">
                  <a role="button" tabindex="0" aria-label="Ir al sitio web Inundaciones La Plata."
                    id="dondeir6"
                    style="color: rgb(255, 255, 255);"> Ir al sitio web</a>
                </div>
              </div>
            </div>
          </div>
          <!-- juego 8 -->
          <div class="card" tabindex="0">
            <img role="img" class="img-juego img1"
              src="{{url_for('static', filename = 'img/section5/dondeir-tapa/AyudAR.webp')}}"
              alt=" Ayud-AR."
              aria-label="Tapa del sitio web Ayud-AR.">
            <div class="intro">
              <h2>
                Ayud-AR
              </h2>
              <p class="esconder-detail">
                Aplicacion web de prevención de inundaciones, puedes ver puntos de encuentros, mapas de denuncias, mapas de zonas inundables.  
              </p>
              <div aria-labelledby="diario-2">
                <div class="verde-4 esconder-detail boton">
                  <a role="button" tabindex="0" aria-label="Ir al sitio web Ayud-AR."
                    id="dondeir7" style="color: rgb(255, 255, 255);"> Ir al sitio web</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- boton para ir arriba -->
  {% include ('partials/_button.html') %}
</main>
{% endblock %}

templates/recomendacion-como-actuar.html
<!-- Contenedor del testimonio -->
{% extends 'partials/_layout.html' %} {% block body %}
<!-- Info de recomendaciones de como actuar-->
<main>
  <div class="contenedor-testimonio">
    <div id="afiche-header" class="afiche__head">
      <h1 id="contenido" class="centrar-texto text-shadow" tabindex="0">
        Recomendaciones sobre cómo actuar.
      </h1>
    </div>
    <!-- segundo componente -->
    <div class="flex__container-column">
      <div class="grid__texto">
        <div class="flex__container2" tabindex="0">
          <p>
            En el Manual del Plan de Reducción del Riesgo por Inundaciones para
            la Región La Plata, se lista una serie de recomendaciones de cómo
            actuar frente a inundaciones. Aquí te mostramos algunas:
          <br>
             Seleccione los botones verdes para conocerlos.
          </p>
        </div>
      </div>
    </div>
    <!-- tercer componente  -->
    <div class="grid__container__4">
      <!-- elemento n -->
      {% for reco in recommendations %}
      <div class="grid__image mg-top">
        <img
          tabindex="0"
          aria-label={{reco.imgAriaLabel}}
          role="img"
          width="50%"
          height="50%"
          src="{{url_for('static', filename = reco.img)}}"
          alt={{reco.imgAriaLabel}}
        />

        <!-- componente 1 -->
        <div class="accordion">
          <button
            type="button"
            aria-label={{reco.btnAriaLabel}}
            aria-expanded="false"
            aria-controls="sect{{loop.index}}"
            aria-labelledby="accordion1id-{{loop.index}}"
            class="accordion-trigger boton-acordeon verde-4"
          >
            <span class="accordion-title">
              {{reco.btnTitle}}
              <svg
                id="campo"
                xmlns="http://www.w3.org/2000/svg"
                class="down"
                fill="#fff"
                width="12"
                height="9"
                viewBox="0 0 12 9"
              >
                <polygon points="1 0, 11 0, 6 8"></polygon>
              </svg>
            </span>
          </button>

          <div id="sect{{loop.index}}" role="region" class="accordion-panel" hidden>
            <div style="width: 100%">
              <fieldset tabindex="0" id="accordion1id-{{loop.index}}">
                <div class="curso__descripcion">
                  <p>{{reco.description}}</p>
                </div>
              </fieldset>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <!-- fila 2 -->
    <div class="flex__container-column">
      <div class="grid__texto">
        <div tabindex="0" class="flex__container2">
          <p>
            - Si estás en una casa y el agua supera las rodillas, aseguráte de
            tener una abertura disponible para no quedar atrapado. Dejá la
            heladera abierta para que no flote.
          </p>
          <p>
            - Si estás en el auto y el agua ya ingresa al vehículo, conviene
            salir y buscar refugio.
          </p>
        </div>
      </div>
    </div>
  </div>
  <!-- boton para ir arriba -->
  {% include ('partials/_button.html') %}
</main>
<!-- script -->
<!-- ver mas del testimonio  -->
<!-- FIN Info de recomendaciones de como actuar-->
{% endblock %}

templates/soluciones_naturales .html
  <!-- Contenedor del testimonio -->
  {% extends 'partials/_layout.html' %}
  {% block body %}
  <!-- Info del Contenedor del video-->
  <main>
   
        <div class="main-card">
          <div class="main-card-body">
            <div id="afiche-header" class="afiche__head">
              <h1 id="contenido" tabindex="0" class="centrar-texto">Soluciones basadas en la naturaleza</h1>
            </div>
            
                
                <!-- detalles del video -->
                <div tabindex="0" class="grid__texto flex__container_dondeir">
                    
                    <div class="video__descripcion">
                      <p >
                        El proyecto Citadine – Ciencia ciudadana para la gestión de catástrofes y soluciones basadas en la naturaleza- desarrolló dos sitios de referencia con toda la información recabada durante el proyecto. En el sitio de Soluciones basadas en la naturaleza o NBS, se encuentran distintas alternativas que pueden emprender los ciudadanos para lograr una ciudad más sustentable.
                        Seleccione el sitio de soluciones basadas en la naturaleza del proyecto Citadine. Se abrirá una pestaña del navegador para el acceso al mismo.

                      </p>
                    </div>
                    
                   
                    <!-- 1 imagen -->
                    <div  class="grid__container__2">
                      <div class="grid__image">
                              <img role="img" width="100%" height="100%" src="{{url_for('static', filename = 'img/section6/solucion.webp')}}" aria-label="Imagen del Sitio web de soluciones basadas en la naturaleza." alt="Imagen del Sitio web de soluciones basadas en la naturaleza.">
                              
                                <small class="contenedor__text" style="width: 50%;">
                                    Foto: Sitio web de soluciones basadas en la naturaleza."
                                </small>
                        </div>
                    </div>
                    
                    <!-- boton jugar-->
                    <div class="verde-4 boton" style="width: 50%;">
                      <a class="citadineVerde" style="color: rgb(255, 255, 255);" > Ir al sitio de Citadine-NBS</a>
                    </div>
                  
                </div>
                <!-- fin del contenedor   -->
            
          </div>
        </div>
        <!-- boton para ir arriba -->
        {% include ('partials/_button.html') %}  
  </main>
  
 <!-- FIN Info del contenedor de video -->
 {% endblock %}